### ISSUE TITLE
ValueError: Language not supported: ISO 639-1 Code

### ISSUE THREAD

**Issue by ptrstn** [dewittethomas/text-to-speech#1]
Hello,

I was trying to use your package and run the example code provided:

```python
import text_to_speech as speech

speech.speak("text", "ISO 639-1 Code")
```

Which returned the following error message:

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/bla/bla/blubb/venv/lib/python3.8/site-packages/text_to_speech/text_to_speech.py", line 17, in speak
    tts = gTTS(text=text, lang=lang)
  File "/home/bla/bla/blubb/venv/lib/python3.8/site-packages/gtts/tts.py", line 131, in __init__
    raise ValueError("Language not supported: %s" % lang)
ValueError: Language not supported: ISO 639-1 Code
```

I am using  ```Python``` version ```3.8.3```, ```text-to-speech``` version ```1.2.2``` and installed it via:

```bash
pip install text-to-speech
```

**Comment by dewittethomas** [comment]
Oh sorry, that I haven't explained it well but now you can see a beter example in the readme.md, actually you have to put in which language you want the module to speak out the text, for example: fr for french and en for english, I hope this helped you, contact me later if you have some questions.

**Comment by dewittethomas** [comment]
The input needs to be an  ISO 639-1 Code
