### ISSUE TITLE
Can't find documentation.

### ISSUE THREAD

**Issue by AlisterBaroi** [dewittethomas/text-to-speech#2]
Hi, 
I've recently been searching for some open-source TTP python packages/API, and have happened to stumble upon this text-to-speech project. I imported and tried to play around with it a bit. Although I really like this project, I can't seem to find any documentation on it. If there is any documentation of this project, please let me know, cause I really want to move forward with this project.

Thanks 
Alister

**Comment by dewittethomas** [comment]
Hi,
Oh thank you Alister, you can just change the language or the text so the package is very limited right now but i've given a bit more information in the documentation.

Thomas
