### ISSUE TITLE
#Permission_denied_fix

### ISSUE THREAD

**Issue by Cyborg117** [dewittethomas/text-to-speech#4]
Since all files are being saved as 'speech.mp3', it works for the first time but after that it gives "**_Errno 13 Permission denied file: speech.mp3_**" so I am suggesting an edit to everybody to goto the Text_to_speech folder(in your python base directory) and then open the "text_to_speech.py" in your IDE and delete everything and paste this:

`import os
from gtts import gTTS
from playsound import playsound
from datetime import datetime

def play(file):
    playsound(file, True)

def speak(text, lang = "en", slow = False, save = False, file = ""):
    dt=datetime.now().strftime("%d%m%Y%H%M%S")
    if save == True and file != "":
        file = file
    elif save == True and file == "":
        file = "speech"+dt+".mp3"
    elif save == False:
        file = "speech"+dt+".mp3"
    else:
        raise ValueError(f"'{file}' is not defined")
    
    if slow == True:
        slow = True
    elif slow ==  False:
        slow = False
    else:
        raise ValueError(f"'{slow}' is not defined")
    
    tts = gTTS(text=text, lang=lang, slow=slow)

    if os.path.splitext(file)[1] == ".mp3":
        tts.save(file)
        
        play(file)

        if save == False:
            os.unlink(file)
        elif save == True:
            pass
        else:
            raise ValueError(f"'{save}' is not defined")
    else:
        raise ValueError(f"'{file}' is not a valid mp3 format")
`

I just used datetime to change filenames. 
\\Happy Coding

**Comment by dewittethomas** [comment]
Thanks Cyborg117, I'll update it!
