### ISSUE TITLE
No sound terminal

### ISSUE THREAD

**Issue by 007fred50** [dewittethomas/text-to-speech#5]
Hello,'

i have installed the plugin (https://pypi.org/project/text-to-speech/)

But then i try to test it,
there are no sound in terminal

```
from text_to_speech import speak 

speak("hello")
```

i try to install it on raspberry pi, there are sound in youtube, and command(play ****.mp3)

can you help me out?

**Comment by 007fred50** [comment]
there are no sound on python at all.

**Comment by dewittethomas** [comment]
So do you mean that you don't hear any sound if I understand correctly?

**Comment by 007fred50** [comment]
yes, no sound at all

**Comment by GomesMarcos** [comment]
I got "ModuleNotFoundError: No module named 'gi '" on "playsound.py", line 91.
pip install gi doesn't solved it. =\

**Comment by dewittethomas** [comment]
> 
> 
> I got "ModuleNotFoundError: No module named 'gi '" on "playsound.py", line 91.
> pip install gi doesn't solved it. =\

Try un-installing my module and reinstalling it, that should fix it because it's an error with the module I use (playsound).

**Comment by dewittethomas** [comment]
> 
> 
> Hello,'
> 
> i have installed the plugin (https://pypi.org/project/text-to-speech/)
> 
> But then i try to test it,
> there are no sound in terminal
> 
> ```
> from text_to_speech import speak 
> 
> speak("hello")
> ```
> 
> i try to install it on raspberry pi, there are sound in youtube, and command(play ****.mp3)
> 
> can you help me out?

What do you mean "there are sound in youtube, and command(play ****.mp3)"?

**Comment by dewittethomas** [comment]
The module is Windows-only from now, so you can't use it anymore on Linux.
